name: cool_stepper_reloaded
description: CoolStepper Reloaded is a new widget based on CoolStepper, that displays a step by step sequence of operations. it could be helpful for a form wizard or onboarding.
version: 2.1.0
homepage: https://github.com/lcsvcn/cool-stepper-reloaded/
repository: https://github.com/lcsvcn/cool-stepper-reloaded/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.10.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
